'use strict';
const API=(window.GPUBNB_CONFIG?.apiBase||window.GPUBNB_API_URL||'').replace(/\/$/,'');
async function accountApi(path,options={}){const response=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`Erreur API (${response.status})`);error.status=response.status;throw error}return data}
function requireAccount(error){if(error?.status===401){const next=location.pathname.includes('onboarding')?'onboarding':location.pathname.includes('dashboard')?'dashboard':'index';location.href=`auth.html?next=${encodeURIComponent(next)}`;return true}return false}
async function logout(){try{await accountApi('/auth/logout',{method:'POST',body:'{}'})}finally{location.href='index.html'}}
document.querySelectorAll('[data-logout]').forEach(button=>button.addEventListener('click',logout));

async function initOnboarding(){
 const form=document.querySelector('#profileForm');if(!form)return;const message=document.querySelector('#profileMessage');
 try{const {user}=await accountApi('/profile');for(const name of ['pseudonym','firstName','lastName','phone','countryCode','language'])if(form.elements[name])form.elements[name].value=user[name]||'';for(const name of ['bio','companyName','websiteUrl','avatarUrl'])if(form.elements[name])form.elements[name].value=user.profile?.[name]||'';form.elements.canRent.checked=user.canRent;form.elements.canHost.checked=user.canHost;document.querySelector('#privateEmail').textContent=user.email||'Compte Phantom';}
 catch(error){if(!requireAccount(error))message.textContent='Impossible de charger le profil.'}
 form.addEventListener('submit',async event=>{event.preventDefault();message.textContent='Enregistrement…';const value=name=>String(form.elements[name].value||'').trim();const nullable=name=>value(name)||null;try{await accountApi('/profile',{method:'PUT',body:JSON.stringify({pseudonym:value('pseudonym'),firstName:value('firstName'),lastName:value('lastName'),phone:nullable('phone'),countryCode:value('countryCode').toUpperCase(),language:value('language'),canRent:form.elements.canRent.checked,canHost:form.elements.canHost.checked,bio:nullable('bio'),companyName:nullable('companyName'),websiteUrl:nullable('websiteUrl'),avatarUrl:nullable('avatarUrl')})});message.textContent='Profil enregistré.';const next=new URLSearchParams(location.search).get('next');const allowed=new Set(['dashboard.html','host-install.html','machines.html','listings.html','publish.html']);location.href=allowed.has(next||'')?next:'dashboard.html'}catch(error){message.textContent=error.message==='pseudonym_unavailable'?'Ce pseudo est déjà utilisé.':error.message}});
}

function renderItems(container,items,kind){container.replaceChildren();if(!items.length){container.innerHTML='<p class="empty">Aucune donnée pour le moment.</p>';return}for(const item of items){const article=document.createElement('article');article.className='list-item';const body=document.createElement('div');const title=document.createElement('strong');const detail=document.createElement('p');const badge=document.createElement('span');badge.className='badge';if(kind==='booking'){title.textContent=item.listing.title;detail.textContent=`${new Date(item.startsAt).toLocaleDateString('fr-FR')} · ${(Number(item.quotedLamports)/1e9).toFixed(4)} SOL`;badge.textContent=item.status;if(['FUNDED','STARTING','ACTIVE'].includes(item.status)){const run=document.createElement('button');run.className='button';run.textContent='Ouvrir Compute sécurisé';run.addEventListener('click',async()=>{run.disabled=true;try{const created=await accountApi(`/bookings/${encodeURIComponent(item.id)}/workspace-sessions`,{method:'POST',body:JSON.stringify({workspaceSlug:'compute'})});location.href=`session.html?id=${encodeURIComponent(created.id)}`}catch(error){detail.textContent=error.message;run.disabled=false}});body.append(title,detail,run);article.append(body,badge);container.append(article);continue}}else if(kind==='job'){title.textContent='Diagnostic GPU';detail.textContent=`Créé ${new Date(item.createdAt).toLocaleString('fr-FR')}${item.errorCode?` · ${item.errorCode}`:''}`;badge.textContent=item.status}else if(kind==='listing'){title.textContent=item.title;detail.textContent=`${(Number(item.hourlyLamports)/1e9).toFixed(4)} SOL/h`;badge.textContent=item.status}else{title.textContent=item.gpuModel||'GPU en attente de vérification';detail.textContent=item.lastHeartbeatAt?`Dernier signal ${new Date(item.lastHeartbeatAt).toLocaleString('fr-FR')}`:'Aucun signal reçu';badge.textContent=item.connectivity}body.append(title,detail);if(kind==='machine'){const spaces=document.createElement('a');spaces.className='button';spaces.href=`workspaces.html?machine=${encodeURIComponent(item.id)}`;spaces.textContent='Configurer les espaces';body.append(spaces)}article.append(body,badge);container.append(article)}}

let pairingRequest=null;
async function createHostPairingCode(){
 const button=document.querySelector('#createLinkCode');const output=document.querySelector('#linkCodeResult');if(!button||!output||pairingRequest)return pairingRequest;
 button.disabled=true;button.textContent='Création sécurisée…';output.setAttribute('aria-live','polite');output.textContent='Création du code temporaire…';
 pairingRequest=(async()=>{try{const result=await accountApi('/machines/link-code',{method:'POST',body:'{}'});if(!/^[A-F0-9]{10}$/.test(String(result.code||''))||!Number.isInteger(result.expiresIn)||result.expiresIn<1||result.expiresIn>600)throw new Error('Réponse d’association invalide.');const minutes=Math.ceil(result.expiresIn/60);output.textContent=`Code temporaire : ${result.code}. Copiez-le dans GPUbnb Host. Il expire dans ${minutes} minute${minutes>1?'s':''} et ne peut être utilisé qu’une seule fois.`;}catch(error){output.textContent='';if(!requireAccount(error))output.textContent=error.message||'Impossible de créer le code temporaire.'}finally{pairingRequest=null;button.disabled=false;button.textContent='Créer un nouveau code'}})();
 return pairingRequest;
}

async function initDashboard(){
 const root=document.querySelector('#dashboardRoot');if(!root)return;
 try{const data=await accountApi('/dashboard');if(data.user.needsOnboarding){location.href='onboarding.html';return}document.querySelector('#welcomeName').textContent=data.user.pseudonym;document.querySelector('#tenantBookingCount').textContent=String(data.tenant.bookings.length);document.querySelector('#tenantJobCount').textContent=String(data.tenant.jobs.length);document.querySelector('#hostMachineCount').textContent=String(data.host.machines.length);document.querySelector('#hostListingCount').textContent=String(data.host.listings.length);renderItems(document.querySelector('#tenantBookings'),data.tenant.bookings,'booking');renderItems(document.querySelector('#tenantJobs'),data.tenant.jobs,'job');renderItems(document.querySelector('#hostListings'),data.host.listings,'listing');renderItems(document.querySelector('#hostMachines'),data.host.machines,'machine');const tenantButton=document.querySelector('[data-space="tenant"]');const hostButton=document.querySelector('[data-space="host"]');if(!data.user.canRent)tenantButton.hidden=true;if(!data.user.canHost)hostButton.hidden=true;const activate=space=>{document.querySelectorAll('[data-space]').forEach(x=>x.classList.toggle('active',x.dataset.space===space));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('hidden',x.dataset.panel!==space))};document.querySelectorAll('[data-space]').forEach(x=>x.addEventListener('click',()=>activate(x.dataset.space)));const pairingRequested=new URLSearchParams(location.search).get('pair')==='host';activate(pairingRequested?'host':data.user.canRent?'tenant':'host');if(pairingRequested){const output=document.querySelector('#linkCodeResult');if(output){output.setAttribute('aria-live','polite');output.textContent='Cliquez sur « Créer un nouveau code » lorsque GPUbnb Host est prêt. Aucun code n’est créé automatiquement.';}}}
 catch(error){if(!requireAccount(error))root.innerHTML='<section class="panel">Impossible de charger votre espace.</section>'}
}
const linkButton=document.querySelector('#createLinkCode');if(linkButton)linkButton.addEventListener('click',()=>void createHostPairingCode());
initOnboarding();void initDashboard();
