'use strict';
const API=(window.GPUBNB_API_URL||'').replace(/\/$/,'');
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
let connectedWallet=null;
function encode58(bytes){if(!bytes.length)return '';const digits=[0];for(const byte of bytes){let carry=byte;for(let j=0;j<digits.length;j++){carry+=digits[j]<<8;digits[j]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let out='';for(let k=0;k<bytes.length&&bytes[k]===0;k++)out+='1';for(let q=digits.length-1;q>=0;q--)out+=ALPHABET[digits[q]];return out}
const listings=document.querySelector('#listings'); const status=document.querySelector('#apiStatus'); const accountButton=document.querySelector('#accountButton');
function el(tag,text,className){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(className)x.className=className;return x}
async function jsonFetch(url,options={}){const r=await fetch(`${API}${url}`,{credentials:'include',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function authenticate(){const p=window.solana;if(!p?.isPhantom)throw new Error('Installez Phantom pour continuer.');await p.connect();const wallet=p.publicKey.toString();const n=await jsonFetch('/auth/nonce',{method:'POST',body:JSON.stringify({wallet})});const signed=await p.signMessage(new TextEncoder().encode(n.message),'utf8');await jsonFetch('/auth/verify',{method:'POST',body:JSON.stringify({wallet,message:n.message,signature:encode58(signed.signature)})});connectedWallet=wallet;if(accountButton)accountButton.textContent=`${wallet.slice(0,4)}…${wallet.slice(-4)}`;return p}
async function rentGpuProof(listing){try{const provider=await authenticate();const startsAt=new Date(Date.now()+5*60_000);const endsAt=new Date(startsAt.getTime()+5*60_000);const booking=await jsonFetch('/bookings',{method:'POST',body:JSON.stringify({listingId:listing.id,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),idempotencyKey:crypto.randomUUID()})});const sol=(Number(booking.quotedLamports)/1e9).toFixed(6);if(!confirm(`Bloquer ${sol} SOL dans l'escrow Devnet pour un GPU Proof de 5 minutes ?`))return;const intent=await jsonFetch(`/bookings/${booking.id}/payment-intent`,{method:'POST',body:'{}'});const bytes=Uint8Array.from(atob(intent.transactionBase64),c=>c.charCodeAt(0));const tx=window.solanaWeb3.Transaction.from(bytes);const sent=await provider.signAndSendTransaction(tx);await provider.connection?.confirmTransaction?.(sent.signature);await jsonFetch(`/bookings/${booking.id}/confirm-deposit`,{method:'POST',body:JSON.stringify({signature:sent.signature})});alert(`GPU Proof financé. Le job CUDA démarrera automatiquement.\nTransaction : ${sent.signature}`)}catch(e){console.error(e);alert(`Impossible de terminer : ${e.message}`)}}
function renderCard(x){const card=el('article',undefined,'card');const badge=el('span','● GPU connecté','eyebrow');const title=el('h3',x.title);const desc=el('p',x.description);const meta=el('div',undefined,'meta');const gpu=`${x.machine.gpuModel} · ${x.machine.vramMiB} MiB`;const owner=x.owner.pseudonym;meta.append(el('span',gpu),el('span',owner));const hourlySol=Number(x.hourlyLamports)/1e9;const price=el('div',`${hourlySol.toFixed(4)} SOL/h`,'price');const rent=el('button','Lancer un GPU Proof · 5 min');rent.type='button';rent.addEventListener('click',()=>rentGpuProof(x));card.append(badge,title,desc,meta,price,rent);return card}
async function load(){listings.replaceChildren(el('article','Chargement…','empty'));let remote=[];try{const health=await jsonFetch('/health');status.textContent=`API active · ${health.cluster}`;document.querySelector('#networkWarning').textContent=health.mainnetEnabled?'Mainnet activé — paiements réels.':'Mode test : Mainnet verrouillé.';remote=await jsonFetch('/listings')}catch(e){status.textContent='API indisponible';document.querySelector('#networkWarning').textContent='Connexion API requise.'}
listings.replaceChildren();if(!remote.length){listings.append(el('article','Aucun GPU vérifié et connecté pour le moment.','empty'));return}for(const x of remote)listings.append(renderCard(x))}
document.querySelector('#refresh').addEventListener('click',load);
(async()=>{try{const me=await jsonFetch('/auth/me');if(accountButton){accountButton.textContent=me.user.pseudonym;accountButton.href=me.user.needsOnboarding?'onboarding.html':'dashboard.html';}}catch{}finally{load();}})();
