'use strict';
const API=(window.GPUBNB_API_URL||'').replace(/\/$/,'');
const LOCAL_LISTINGS_KEY='gpubnb.demo.listings.v1';
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
let connectedWallet=null;
function encode58(bytes){if(!bytes.length)return '';const digits=[0];for(const byte of bytes){let carry=byte;for(let j=0;j<digits.length;j++){carry+=digits[j]<<8;digits[j]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let out='';for(let k=0;k<bytes.length&&bytes[k]===0;k++)out+='1';for(let q=digits.length-1;q>=0;q--)out+=ALPHABET[digits[q]];return out}
const listings=document.querySelector('#listings'); const status=document.querySelector('#apiStatus'); const walletButton=document.querySelector('#wallet');
function el(tag,text,className){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(className)x.className=className;return x}
function getLocalListings(){try{const data=JSON.parse(localStorage.getItem(LOCAL_LISTINGS_KEY)||'[]');return Array.isArray(data)?data:[]}catch{return []}}
async function jsonFetch(url,options={}){const r=await fetch(`${API}${url}`,{credentials:'include',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function authenticate(){const p=window.solana;if(!p?.isPhantom)throw new Error('Installez Phantom pour continuer.');await p.connect();const wallet=p.publicKey.toString();const n=await jsonFetch('/auth/nonce',{method:'POST',body:JSON.stringify({wallet})});const signed=await p.signMessage(new TextEncoder().encode(n.message),'utf8');await jsonFetch('/auth/verify',{method:'POST',body:JSON.stringify({wallet,message:n.message,signature:encode58(signed.signature)})});connectedWallet=wallet;walletButton.textContent=`${wallet.slice(0,4)}…${wallet.slice(-4)}`;return p}
async function rentOneHour(listing){if(listing.isLocalDemo){alert(`Démo locale : “${listing.title}” serait réservée pour 1 heure à ${listing.hourlySol.toFixed(4)} SOL.\nAucune transaction n'a été envoyée.`);return}try{const provider=await authenticate();const startsAt=new Date(Date.now()+5*60_000);const endsAt=new Date(startsAt.getTime()+60*60_000);const booking=await jsonFetch('/bookings',{method:'POST',body:JSON.stringify({listingId:listing.id,startsAt:startsAt.toISOString(),endsAt:endsAt.toISOString(),idempotencyKey:crypto.randomUUID()})});const sol=(Number(booking.quotedLamports)/1e9).toFixed(6);if(!confirm(`Bloquer ${sol} SOL dans l'escrow pour une location d'une heure ?`))return;const intent=await jsonFetch(`/bookings/${booking.id}/payment-intent`,{method:'POST',body:'{}'});const bytes=Uint8Array.from(atob(intent.transactionBase64),c=>c.charCodeAt(0));const tx=window.solanaWeb3.Transaction.from(bytes);const sent=await provider.signAndSendTransaction(tx);await provider.connection?.confirmTransaction?.(sent.signature);await jsonFetch(`/bookings/${booking.id}/confirm-deposit`,{method:'POST',body:JSON.stringify({signature:sent.signature})});alert(`Paiement confirmé. Réservation financée.\nTransaction : ${sent.signature}`)}catch(e){console.error(e);alert(`Impossible de terminer : ${e.message}`)}}
function renderCard(x){const card=el('article',undefined,'card');const isLocal=Boolean(x.isLocalDemo);const badge=el('span',isLocal?'● Annonce locale · Démo':'● GPU connecté','eyebrow');const title=el('h3',x.title);const desc=el('p',x.description);const meta=el('div',undefined,'meta');const gpu=isLocal?`${x.gpuModel} · ${x.vramGb} GB VRAM`:`${x.machine.gpuModel} · ${x.machine.vramMiB} MiB`;const owner=isLocal?`${x.location} · ${x.ownerPseudonym}`:x.owner.pseudonym;meta.append(el('span',gpu),el('span',owner));const hourlySol=isLocal?Number(x.hourlySol):Number(x.hourlyLamports)/1e9;const price=el('div',`${hourlySol.toFixed(4)} SOL/h`,'price');const rent=el('button',isLocal?'Simuler une location':'Louer 1 heure');rent.type='button';rent.addEventListener('click',()=>rentOneHour(x));card.append(badge,title,desc,meta,price,rent);return card}
async function load(){listings.replaceChildren(el('article','Chargement…','empty'));const local=getLocalListings().map(x=>({...x,isLocalDemo:true}));let remote=[];try{const health=await jsonFetch('/health');status.textContent=`API active · ${health.cluster}`;document.querySelector('#networkWarning').textContent=health.mainnetEnabled?'Mainnet activé — paiements réels.':'Mode test : Mainnet verrouillé.';remote=await jsonFetch('/listings')}catch(e){status.textContent=local.length?'API indisponible · annonces locales actives':'API indisponible';document.querySelector('#networkWarning').textContent='La démonstration locale reste disponible.'}
listings.replaceChildren();const all=[...local,...remote];if(!all.length){listings.append(el('article','Aucun GPU vérifié ou publié localement pour le moment.','empty'));return}for(const x of all)listings.append(renderCard(x))}
document.querySelector('#refresh').addEventListener('click',load);walletButton.addEventListener('click',()=>authenticate().catch(e=>alert(e.message)));window.addEventListener('storage',event=>{if(event.key===LOCAL_LISTINGS_KEY)load()});load();
