'use strict';
const API=(window.GPUBNB_API_URL||'').replace(/\/$/,'');
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
let connectedWallet=null;
function encode58(bytes){if(!bytes.length)return '';const digits=[0];for(const byte of bytes){let carry=byte;for(let j=0;j<digits.length;j++){carry+=digits[j]<<8;digits[j]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let out='';for(let k=0;k<bytes.length&&bytes[k]===0;k++)out+='1';for(let q=digits.length-1;q>=0;q--)out+=ALPHABET[digits[q]];return out}
const listings=document.querySelector('#listings'); const status=document.querySelector('#apiStatus'); const accountButton=document.querySelector('#accountButton');
function el(tag,text,className){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(className)x.className=className;return x}
async function jsonFetch(url,options={}){const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined&&!('content-type' in headers)&&!('Content-Type' in headers))headers['content-type']='application/json';const r=await fetch(`${API}${url}`,{credentials:'include',...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
async function authenticate(){const p=window.solana;if(!p?.isPhantom)throw new Error('Installez Phantom pour continuer.');await p.connect();const wallet=p.publicKey.toString();const n=await jsonFetch('/auth/nonce',{method:'POST',body:JSON.stringify({wallet})});const signed=await p.signMessage(new TextEncoder().encode(n.message),'utf8');await jsonFetch('/auth/verify',{method:'POST',body:JSON.stringify({wallet,message:n.message,signature:encode58(signed.signature)})});connectedWallet=wallet;if(accountButton)accountButton.textContent=`${wallet.slice(0,4)}…${wallet.slice(-4)}`;return p}
function renderCard(x){const card=el('article',undefined,'card');const busy=x.availability?.state&&x.availability.state!=='AVAILABLE';const badge=el('span',busy?`● ${x.availability.label}`:'● GPU vérifié','eyebrow');const title=el('h3',x.title);const desc=el('p',x.description);const meta=el('div',undefined,'meta');const gpu=`${x.gpu.vendor?`${x.gpu.vendor} `:''}${x.gpu.model} · ${x.gpu.vramMiB} MiB`;const owner=x.owner.pseudonym;meta.append(el('span',gpu),el('span',owner));const hourlySol=Number(x.hourlyLamports)/1e9;const price=el('div',`${hourlySol.toFixed(4)} SOL/h`,'price');let choose;if(busy){const availableAt=x.availability.availableAt?new Date(x.availability.availableAt).toLocaleString('fr-FR'):'';choose=el('button',availableAt?`${x.availability.label} jusqu’au ${availableAt}`:x.availability.label,'button button-secondary');choose.disabled=true}else{choose=el('a','Choisir ce GPU et mon espace','button button-primary');choose.href=`choose-workspace.html?listing=${encodeURIComponent(x.id)}`}card.append(badge,title,desc,meta,price,choose);return card}
async function load(){listings.replaceChildren(el('article','Chargement…','empty'));let remote=[];try{const health=await jsonFetch('/health');status.textContent=`API active · ${health.cluster}`;document.querySelector('#networkWarning').textContent=health.mainnetEnabled?'Mainnet activé — paiements réels.':'Mode test : Mainnet verrouillé.';remote=await jsonFetch('/rental/listings')}catch(e){console.error(e);status.textContent='API indisponible';document.querySelector('#networkWarning').textContent='Connexion API requise.'}
listings.replaceChildren();if(!remote.length){listings.append(el('article','Aucun GPU vérifié et connecté pour le moment.','empty'));return}for(const x of remote)listings.append(renderCard(x))}
document.querySelector('#refresh').addEventListener('click',load);
(async()=>{try{const me=await jsonFetch('/auth/me');if(accountButton){accountButton.textContent=me.user.pseudonym;accountButton.href=me.user.needsOnboarding?'onboarding.html':'dashboard.html';}}catch{}finally{load();}})();
