'use strict';
const cfg=window.GPUBNB_AUTH_CONFIG||{};
const API=(window.GPUBNB_CONFIG?.apiBase||'').replace(/\/$/,'');
const statusEl=document.querySelector('#status');
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function encode58(bytes){if(!bytes.length)return '';const digits=[0];for(const byte of bytes){let carry=byte;for(let j=0;j<digits.length;j++){carry+=digits[j]<<8;digits[j]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let out='';for(let k=0;k<bytes.length&&bytes[k]===0;k++)out+='1';for(let q=digits.length-1;q>=0;q--)out+=ALPHABET[digits[q]];return out}
const setStatus=(m,e=false)=>{statusEl.textContent=m;statusEl.style.color=e?'#ff8b8b':'#73ffb7'};
async function api(path,options={}){const r=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Erreur API');return data;}
function supabaseClient(){if(!cfg.supabaseUrl||!cfg.supabaseAnonKey||cfg.supabaseUrl.includes('YOUR_PROJECT'))throw new Error('Configure auth-config.js avec ton projet Supabase');return window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
async function exchangeSupabase(client){const {data:{session}}=await client.auth.getSession();if(!session)throw new Error('Session Supabase absente');await api('/auth/supabase',{method:'POST',body:JSON.stringify({accessToken:session.access_token})});}
async function ensureProfile(client,pseudonym){const {data:{user}}=await client.auth.getUser();if(!user)return;const clean=(pseudonym||`user_${user.id.slice(0,8)}`).replace(/[^A-Za-z0-9_-]/g,'_').slice(0,32);const {error}=await client.from('profiles').upsert({id:user.id,pseudonym:clean},{onConflict:'id'});if(error&&!String(error.message).includes('duplicate'))throw error;}
document.querySelector('#google').addEventListener('click',async()=>{try{const client=supabaseClient();setStatus('Redirection vers Google…');const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:cfg.redirectUrl||location.href}});if(error)throw error}catch(e){setStatus(e.message||'Erreur Google',true)}});
document.querySelector('#phantom').addEventListener('click',async()=>{try{const wallet=window.phantom?.solana||window.solana;if(!wallet?.isPhantom)throw new Error('Phantom n’est pas installé');await wallet.connect();const publicKey=wallet.publicKey.toString();setStatus('Signature Phantom en cours…');const nonce=await api('/auth/nonce',{method:'POST',body:JSON.stringify({wallet:publicKey})});const signed=await wallet.signMessage(new TextEncoder().encode(nonce.message),'utf8');const signature=encode58(signed.signature);await api('/auth/verify',{method:'POST',body:JSON.stringify({wallet:publicKey,message:nonce.message,signature})});location.href='/publish.html';}catch(e){setStatus(e.message||'Erreur Phantom',true)}});
document.querySelector('#email-form').addEventListener('submit',async(e)=>{e.preventDefault();try{const client=supabaseClient();const email=document.querySelector('#email').value.trim();const password=document.querySelector('#password').value;const pseudonym=document.querySelector('#pseudonym').value.trim();setStatus('Vérification…');let result=await client.auth.signInWithPassword({email,password});if(result.error){result=await client.auth.signUp({email,password,options:{emailRedirectTo:cfg.redirectUrl||location.href}});if(result.error)throw result.error;if(!result.data.session){setStatus('Compte créé. Vérifie ton e-mail.');return}}await ensureProfile(client,pseudonym);await exchangeSupabase(client);location.href='/publish.html';}catch(err){setStatus(err.message||'Erreur',true)}});
(async()=>{try{const client=supabaseClient();const {data:{session}}=await client.auth.getSession();if(session){await ensureProfile(client,'');await exchangeSupabase(client);setStatus('Connexion réussie');if(location.hash||location.search)location.href='/publish.html';}}catch{}})();
