'use strict';
const cfg=window.GPUBNB_AUTH_CONFIG||{};
const API=(window.GPUBNB_CONFIG?.apiBase||window.GPUBNB_API_URL||'').replace(/\/$/,'');
const statusEl=document.querySelector('#status');
const configHelp=document.querySelector('#config-help');
const ALPHABET='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
function encode58(bytes){if(!bytes.length)return '';const digits=[0];for(const byte of bytes){let carry=byte;for(let j=0;j<digits.length;j++){carry+=digits[j]<<8;digits[j]=carry%58;carry=(carry/58)|0}while(carry){digits.push(carry%58);carry=(carry/58)|0}}let out='';for(let k=0;k<bytes.length&&bytes[k]===0;k++)out+='1';for(let q=digits.length-1;q>=0;q--)out+=ALPHABET[digits[q]];return out}
const setStatus=(m,e=false)=>{statusEl.textContent=m;statusEl.style.color=e?'#ff8b8b':'#73ffb7'};
async function api(path,options={}){const r=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json',...(options.headers||{})},...options});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`Erreur API (${r.status})`);return data;}
function configured(){return Boolean(cfg.supabaseUrl&&cfg.supabaseAnonKey&&!cfg.supabaseUrl.includes('YOUR_PROJECT')&&!cfg.supabaseAnonKey.includes('YOUR_PUBLIC'));}
let sharedSupabaseClient;
function supabaseClient(){if(!configured()){configHelp.hidden=false;throw new Error('Connexion Google/e-mail non configurée : complétez auth-config.js');}if(!window.supabase?.createClient)throw new Error('Le module Supabase n’a pas pu être chargé');sharedSupabaseClient ||= window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});return sharedSupabaseClient}
function destination(needsOnboarding=false){if(needsOnboarding)return 'onboarding.html';const next=new URLSearchParams(location.search).get('next');return next==='publish'?'publish.html':'dashboard.html';}
async function exchangeSupabase(client){const {data:{session},error}=await client.auth.getSession();if(error)throw error;if(!session)throw new Error('Session Supabase absente');return api('/auth/supabase',{method:'POST',body:JSON.stringify({accessToken:session.access_token})});}
document.querySelector('#google').addEventListener('click',async()=>{try{const client=supabaseClient();setStatus('Redirection vers Google…');const redirectTo=cfg.redirectUrl||`${location.origin}/auth.html?next=publish`;const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)throw error}catch(e){setStatus(e.message||'Erreur Google',true)}});
document.querySelector('#phantom').addEventListener('click',async()=>{try{const wallet=window.phantom?.solana||window.solana;if(!wallet?.isPhantom)throw new Error('Phantom n’est pas installé');await wallet.connect();const publicKey=wallet.publicKey.toString();setStatus('Signature Phantom en cours…');const nonce=await api('/auth/nonce',{method:'POST',body:JSON.stringify({wallet:publicKey})});const signed=await wallet.signMessage(new TextEncoder().encode(nonce.message),'utf8');await api('/auth/verify',{method:'POST',body:JSON.stringify({wallet:publicKey,message:nonce.message,signature:encode58(signed.signature)})});location.href=destination(true);}catch(e){setStatus(e.message||'Erreur Phantom',true)}});
document.querySelector('#email-form').addEventListener('submit',async(e)=>{e.preventDefault();try{const client=supabaseClient();const email=document.querySelector('#email').value.trim();const password=document.querySelector('#password').value;const pseudonym=document.querySelector('#pseudonym').value.trim();setStatus('Connexion en cours…');let result=await client.auth.signInWithPassword({email,password});if(result.error){result=await client.auth.signUp({email,password,options:{data:{pseudonym},emailRedirectTo:cfg.redirectUrl||`${location.origin}/auth.html`}});if(result.error)throw result.error;if(!result.data.session){setStatus('Compte créé. Ouvrez l’e-mail de confirmation avant de vous connecter.');return}}const exchanged=await exchangeSupabase(client);location.href=destination(exchanged.user.needsOnboarding);}catch(err){setStatus(err.message||'Erreur de connexion',true)}});
(async()=>{try{if(!configured()){configHelp.hidden=false;return;}const client=supabaseClient();const {data:{session}}=await client.auth.getSession();if(session){setStatus('Finalisation de la connexion…');const exchanged=await exchangeSupabase(client);location.href=destination(exchanged.user.needsOnboarding);}}catch(e){setStatus(e.message||'Impossible de finaliser la connexion',true)}})();
