'use strict';
const cfg=window.GPUBNB_AUTH_CONFIG; const statusEl=document.querySelector('#status');
if(!cfg?.supabaseUrl||!cfg?.supabaseAnonKey) throw new Error('Configuration Supabase manquante');
const client=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const setStatus=(m,e=false)=>{statusEl.textContent=m;statusEl.style.color=e?'#ff8b8b':'#73ffb7'};
async function ensureProfile(pseudonym){const {data:{user}}=await client.auth.getUser(); if(!user)return; const clean=(pseudonym||`user_${user.id.slice(0,8)}`).trim(); const {error}=await client.from('profiles').upsert({id:user.id,pseudonym:clean},{onConflict:'id'}); if(error) throw error;}
document.querySelector('#google').addEventListener('click',async()=>{setStatus('Redirection vers Google…');const {error}=await client.auth.signInWithOAuth({provider:'google',options:{redirectTo:cfg.redirectUrl}});if(error)setStatus(error.message,true)});
document.querySelector('#phantom').addEventListener('click',async()=>{try{const wallet=window.phantom?.solana||window.solana;if(!wallet?.isPhantom)throw new Error('Phantom n’est pas installé');await wallet.connect();setStatus('Signature Phantom en cours…');const {error}=await client.auth.signInWithWeb3({chain:'solana',statement:'Je me connecte à GPUbnb et j’accepte les conditions d’utilisation.',wallet});if(error)throw error;await ensureProfile('');setStatus('Connexion réussie');location.href='/';}catch(e){setStatus(e instanceof Error?e.message:'Erreur Phantom',true)}});
document.querySelector('#email-form').addEventListener('submit',async(e)=>{e.preventDefault();const email=document.querySelector('#email').value.trim();const password=document.querySelector('#password').value;const pseudonym=document.querySelector('#pseudonym').value.trim();try{setStatus('Vérification…');let {error}=await client.auth.signInWithPassword({email,password});if(error){const signup=await client.auth.signUp({email,password,options:{emailRedirectTo:cfg.redirectUrl}});if(signup.error)throw signup.error;if(!signup.data.session){setStatus('Compte créé. Vérifie ton e-mail.');return}}await ensureProfile(pseudonym);setStatus('Connexion réussie');location.href='/';}catch(err){setStatus(err instanceof Error?err.message:'Erreur',true)}});
client.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session)await ensureProfile('')});
