'use strict';
const DEMANDS_KEY='gpubnb.demo.demands.v1';
const PROPOSALS_KEY='gpubnb.demo.proposals.v1';
const form=document.querySelector('#demandForm');const list=document.querySelector('#demandList');const count=document.querySelector('#demandCount');const message=document.querySelector('#formMessage');const description=form.elements.description;const descriptionCount=document.querySelector('#descriptionCount');
function read(key){try{const x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}function write(key,x){localStorage.setItem(key,JSON.stringify(x))}function text(v){return String(v??'')}function field(name){return text(form.elements[name].value).trim()}
function removeDemand(id){write(DEMANDS_KEY,read(DEMANDS_KEY).filter(x=>x.id!==id));write(PROPOSALS_KEY,read(PROPOSALS_KEY).filter(x=>x.demandId!==id));render();message.textContent='Demande supprimée.';message.className='form-message success'}
function render(){const items=read(DEMANDS_KEY);count.textContent=String(items.length);list.replaceChildren();if(!items.length){const p=document.createElement('p');p.className='panel-empty';p.textContent='Aucune demande publiée.';list.append(p);return}for(const item of items){const card=document.createElement('article');card.className='local-listing demand-item';const content=document.createElement('div');const h=document.createElement('h3');h.textContent=text(item.title);const meta=document.createElement('p');meta.textContent=`${item.quantity} × ${text(item.gpuModel)} · ${item.vramGb} GB min · ${Number(item.budgetSol).toFixed(4)} SOL/h`;const detail=document.createElement('span');detail.textContent=`${item.durationHours} h · ${text(item.clientPseudonym)} · ${read(PROPOSALS_KEY).filter(p=>p.demandId===item.id).length} proposition(s)`;content.append(h,meta,detail);const actions=document.createElement('div');actions.className='item-actions';const propose=document.createElement('a');propose.className='mini-action';propose.href=`propositions.html?demand=${encodeURIComponent(item.id)}`;propose.textContent='Proposer';const remove=document.createElement('button');remove.type='button';remove.className='delete-listing';remove.textContent='Supprimer';remove.addEventListener('click',()=>removeDemand(item.id));actions.append(propose,remove);card.append(content,actions);list.append(card)}}
description.addEventListener('input',()=>descriptionCount.value=String(description.value.length));
form.addEventListener('submit',e=>{e.preventDefault();message.textContent='';message.className='form-message';if(!form.reportValidity())return;const item={id:`demand-${Date.now()}-${crypto.randomUUID?.()||Math.random().toString(36).slice(2)}`,title:field('title'),gpuModel:field('gpuModel'),quantity:Number(form.elements.quantity.value),vramGb:Number(form.elements.vramGb.value),budgetSol:Number(form.elements.budgetSol.value),startsAt:form.elements.startsAt.value,durationHours:Number(form.elements.durationHours.value),cuda:field('cuda'),os:field('os'),dockerRequired:form.elements.dockerRequired.checked,clientPseudonym:field('clientPseudonym'),description:field('description'),status:'OPEN',createdAt:new Date().toISOString()};const items=read(DEMANDS_KEY);items.unshift(item);write(DEMANDS_KEY,items);form.reset();form.elements.quantity.value='1';form.elements.durationHours.value='24';descriptionCount.value='0';message.textContent='Demande publiée. Les propriétaires peuvent maintenant proposer leur GPU.';message.className='form-message success';render()});
document.querySelector('#resetForm').addEventListener('click',()=>{form.reset();form.elements.quantity.value='1';form.elements.durationHours.value='24';descriptionCount.value='0';message.textContent='';message.className='form-message'});render();