'use strict';
const API=(window.GPUBNB_API_URL||'').replace(/\/$/,'');
const labels={provider_role_required:"Activez d’abord l’espace propriétaire dans votre profil.",invalid_or_expired_link_code:"Ce code a expiré. Créez-en un nouveau.",internal_error:"Le service rencontre un problème. Réessayez plus tard.",unauthorized:"Connectez-vous pour continuer."};
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function request(path,options={}){const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined&&!('content-type' in headers)&&!('Content-Type' in headers))headers['content-type']='application/json';const response=await fetch(`${API}${path}`,{credentials:'include',...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok){const code=data.error||`HTTP ${response.status}`;const error=new Error(labels[code]||code.replaceAll('_',' '));error.status=response.status;error.code=code;throw error}return data}
function toast(message,error=false){document.querySelector('.toast')?.remove();const node=document.createElement('div');node.className=`toast${error?' error':''}`;node.role='status';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),5000)}
const privatePages=new Set(['dashboard.html','machines.html','listings.html','bookings.html','revenues.html','host-install.html','publish.html']);
function navigation(user){const links=[['dashboard.html','Vue générale'],['index.html#market','Marketplace']];if(user?.canRent)links.push(['bookings.html','Mes réservations'],['demandes.html','Mes demandes'],['workspaces.html','Mes sessions']);if(user?.canHost)links.push(['host-install.html','Installer GPUbnb Host'],['machines.html','Mes machines'],['listings.html','Mes annonces'],['revenues.html','Revenus']);if(user)links.push(['onboarding.html','Profil']);return links}
async function logout(){try{await request('/auth/logout',{method:'POST',body:'{}'})}finally{location.href='index.html'}}
async function shell(){const current=location.pathname.split('/').pop()||'index.html';let user=null;try{user=(await request('/auth/me')).user}catch(error){if(error.status===401&&privatePages.has(current)){location.replace(authHref());return false}}const links=navigation(user).map(([href,label])=>`<a href="${href}">${label}</a>`).join('');document.body.insertAdjacentHTML('afterbegin',`<header class="portal-header"><a class="portal-brand" href="index.html">GPUbnb</a><button class="button mobile-toggle" type="button" aria-expanded="false" aria-controls="portalNav">Menu</button><nav class="portal-nav" id="portalNav" aria-label="Navigation du compte">${links}</nav>${user?'<button class="button" type="button" data-portal-logout>Déconnexion</button>':'<a class="button" href="auth.html">Connexion</a>'}</header>`);document.querySelectorAll('.portal-nav a').forEach(a=>{if(a.getAttribute('href').split('#')[0]===current)a.setAttribute('aria-current','page')});const toggle=document.querySelector('.mobile-toggle');toggle.addEventListener('click',()=>{const nav=document.querySelector('#portalNav');const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});document.querySelector('[data-portal-logout]')?.addEventListener('click',logout);const build=window.GPUBNB_BUILD||{version:'0.2.0',commit:'local',environment:'Devnet',date:'développement'};document.body.insertAdjacentHTML('beforeend',`<footer class="footer">GPUbnb v${escapeHTML(build.version)} · Commit ${escapeHTML(build.commit)} · ${escapeHTML(build.environment)} · Build ${escapeHTML(build.date)}</footer>`);return true}
function empty(container,title,description,href,label){container.innerHTML=`<div class="empty-state"><span class="badge warn">Information</span><h2>${escapeHTML(title)}</h2><p class="muted">${escapeHTML(description)}</p>${href?`<a class="button button-primary" href="${escapeHTML(href)}">${escapeHTML(label)}</a>`:''}</div>`}
function authHref(){const current=location.pathname.split('/').pop()||'dashboard.html';return `auth.html?next=${encodeURIComponent(current)}`}
function errorState(root,title,error){const unauthorized=error?.status===401;empty(root,unauthorized?'Connexion nécessaire':title,unauthorized?'Connectez-vous pour continuer.':(error?.message||'Le service est temporairement indisponible.'),unauthorized?authHref():null,unauthorized?'Se connecter':null)}
function roleLabel(user){if(user.canRent&&user.canHost)return 'Locataire + propriétaire';if(user.canRent)return 'Locataire';if(user.canHost)return 'Propriétaire';return 'Aucun rôle activé'}
function machineReadiness(machine){if(machine.publicationReadiness)return machine.publicationReadiness;if(!machine.lastHeartbeatAt)return {ready:false,reason:'heartbeat_required'};if(machine.connectivity!=='ONLINE')return {ready:false,reason:'machine_offline'};if(!machine.gpuModel)return {ready:false,reason:'gpu_required'};if(!machine.verifiedAt&&machine.operational!=='AVAILABLE')return {ready:false,reason:'diagnostic_required'};return {ready:true,reason:null}}
function nextStep(data){if(data.user.needsOnboarding)return ['Terminer votre profil','Complétez votre profil et choisissez vos rôles.','onboarding.html'];if(!data.user.canHost)return ['Activer l’espace propriétaire','Activez le rôle propriétaire pour connecter une machine.','onboarding.html'];if(!data.host.machines.length)return ['Installer GPUbnb Host','Téléchargez l’application puis créez un code de liaison.','host-install.html'];const readiness=data.host.machines.map(machineReadiness);if(readiness.some(x=>x.reason==='heartbeat_required'))return ['Lancer GPUbnb Host','La machine est créée, mais aucun signal n’a encore été reçu.','machines.html'];if(readiness.some(x=>x.reason==='machine_offline'))return ['Reconnecter la machine','Relancez GPUbnb Host et vérifiez sa connexion.','machines.html'];if(readiness.some(x=>x.reason==='gpu_required'))return ['Détecter le GPU','Vérifiez le pilote NVIDIA et la commande nvidia-smi.','machines.html'];if(readiness.some(x=>x.reason==='diagnostic_required'))return ['Exécuter le diagnostic','Le GPU doit réussir son diagnostic avant publication.','machines.html'];if(!data.host.listings.length)return ['Publier une annonce','Votre machine est prête. Définissez maintenant son offre.','publish.html'];if(data.host.listings.some(x=>x.status!=='ACTIVE'))return ['Finaliser l’annonce','Une annonce existe mais n’est pas encore active.','listings.html'];if(data.tenant.bookings.length)return ['Suivre votre réservation','Consultez son état et les étapes de paiement.','bookings.html'];return ['Rechercher un GPU','Comparez les GPU disponibles sur la marketplace.','index.html#market']}
function updateChecklist(data){const machines=data.host.machines||[];const checks={account:!data.user.needsOnboarding,'host-role':data.user.canHost,'host-download':machines.length>0,'machine-linked':machines.length>0,'machine-online':machines.some(x=>x.connectivity==='ONLINE'),'gpu-detected':machines.some(x=>Boolean(x.gpuModel)),diagnostic:machines.some(machine=>machineReadiness(machine).ready),listing:(data.host.listings||[]).some(x=>x.status==='ACTIVE')};const list=document.querySelector('.checklist');if(list&&!list.querySelector('[data-check]')){list.innerHTML='<li data-check="account">Créer un compte</li><li data-check="host-role">Activer l’espace propriétaire</li><li data-check="host-download">Télécharger GPUbnb Host</li><li data-check="machine-linked">Connecter une machine</li><li data-check="machine-online">Machine en ligne</li><li data-check="gpu-detected">GPU détecté</li><li data-check="diagnostic">Diagnostic réussi</li><li data-check="listing">Publier une annonce</li>'}let pendingSeen=false;document.querySelectorAll('[data-check]').forEach(node=>{const done=Boolean(checks[node.dataset.check]);node.classList.toggle('done',done);node.dataset.state=done?'done':pendingSeen?'todo':'current';if(!done)pendingSeen=true;node.setAttribute('aria-label',`${node.textContent.trim()} : ${done?'terminé':node.dataset.state==='current'?'en cours':'à faire'}`)})}
async function dashboard(){const root=document.querySelector('[data-dashboard]');try{const data=await request('/dashboard');document.querySelector('[data-name]').textContent=data.user.pseudonym;const [title,text,href]=nextStep(data);document.querySelector('[data-next-title]').textContent=title;document.querySelector('[data-next-text]').textContent=text;document.querySelector('[data-next-link]').href=href;document.querySelector('[data-next-link]').textContent=title;document.querySelector('[data-machine-count]').textContent=data.host.machines.length;document.querySelector('[data-listing-count]').textContent=data.host.listings.length;document.querySelector('[data-booking-count]').textContent=data.tenant.bookings.length;document.querySelector('[data-role]').textContent=roleLabel(data.user);document.querySelectorAll('[data-host-only]').forEach(x=>x.hidden=!data.user.canHost);updateChecklist(data)}catch(e){toast(e.message,true);errorState(root,'Tableau de bord indisponible',e)}}
const readinessLabels={heartbeat_required:'Aucun heartbeat reçu',machine_offline:'Relancez GPUbnb Host',gpu_required:'GPU non détecté',diagnostic_required:'Diagnostic CUDA requis',verification_required:'Vérification requise'};
async function machines(){const root=document.querySelector('[data-machines]');try{const rows=await request('/machines/mine');if(!rows.length)return empty(root,'Aucune machine reliée','Installez GPUbnb Host, puis créez un code de liaison.','host-install.html','Installer GPUbnb Host');root.innerHTML=rows.map(x=>{const readiness=machineReadiness(x);return `<article class="list-row machine-detail"><div><strong>${escapeHTML(x.gpuModel||'GPU en détection')}</strong><div class="muted">${escapeHTML(x.operatingSystem||'Système inconnu')}${x.osVersion?` ${escapeHTML(x.osVersion)}`:''} · GPUbnb Host ${escapeHTML(x.agentVersion||'version inconnue')}</div><div class="muted">${x.vramMiB?`${escapeHTML(x.vramMiB)} MiB VRAM · `:''}Pilote ${escapeHTML(x.driverVersion||'inconnu')} · CUDA ${escapeHTML(x.cudaVersion||'non détectée')}</div><div class="muted">${x.lastHeartbeatAt?'Dernier signal '+new Date(x.lastHeartbeatAt).toLocaleString('fr-FR'):'Aucun signal reçu'} · ${x.verifiedAt?'Machine vérifiée':'Non vérifiée'}</div><div class="actions">${readiness.ready?'<a class="button button-primary" href="publish.html">Publier une annonce</a>':'<a class="button" href="host-install.html">Instructions de résolution</a>'}<a class="button" href="workspaces.html">Voir les détails</a></div></div><div><span class="badge ${x.connectivity==='ONLINE'?'ok':'warn'}">${x.connectivity==='ONLINE'?'En ligne':'Hors ligne'}</span><p class="muted">${readiness.ready?'Prête à publier':escapeHTML(readinessLabels[readiness.reason]||'Action nécessaire')}</p></div></article>`}).join('')}catch(e){errorState(root,'Machines indisponibles',e)}}
async function listings(){const root=document.querySelector('[data-listings]');try{const data=await request('/dashboard');const rows=data.host.listings||[];if(!rows.length)return empty(root,'Aucune annonce publiée','Reliez une machine puis créez votre première offre.','publish.html','Publier une annonce');root.innerHTML=rows.map(x=>`<article class="list-row"><div><strong>${escapeHTML(x.title)}</strong><div class="muted">Créée le ${new Date(x.createdAt).toLocaleDateString('fr-FR')} · ${escapeHTML(x.hourlyLamports)} lamports/heure</div></div><span class="badge ${x.status==='ACTIVE'?'ok':'warn'}">${escapeHTML(x.status)}</span></article>`).join('')}catch(e){errorState(root,'Annonces indisponibles',e)}}
async function bookings(){const root=document.querySelector('[data-bookings]');try{const data=await request('/dashboard');const rows=data.tenant.bookings||[];if(!rows.length)return empty(root,'Aucune réservation','Choisissez un GPU disponible pour démarrer un test réel.','index.html#market','Explorer la marketplace');root.innerHTML=rows.map(x=>`<article class="list-row"><div><strong>${escapeHTML(x.listing?.title||'Réservation GPU')}</strong><div class="muted">${new Date(x.startsAt).toLocaleString('fr-FR')} → ${new Date(x.endsAt).toLocaleString('fr-FR')} · ${escapeHTML(x.quotedLamports)} lamports</div></div><span class="badge ${['ACTIVE','SETTLED','FUNDED'].includes(x.status)?'ok':'warn'}">${escapeHTML(x.status)}</span></article>`).join('')}catch(e){errorState(root,'Réservations indisponibles',e)}}
let linkCodeTimer;
let pairingPollTimer;
async function pollPairing(output,baselineIds,expiresIn){clearInterval(pairingPollTimer);const deadline=Date.now()+Math.min(expiresIn,600)*1000;let attempts=0;const status=output.querySelector('[data-pairing-status]');const poll=async()=>{if(Date.now()>=deadline||attempts++>=60){clearInterval(pairingPollTimer);status.textContent='La surveillance est terminée. Générez un nouveau code si nécessaire.';return}try{const rows=await request('/machines/mine');const linked=rows.find(machine=>!baselineIds.has(machine.id));if(!linked){status.textContent='En attente de GPUbnb Host…';return}if(linked.connectivity!=='ONLINE'){status.textContent='Machine liée. En attente du premier signal…';return}if(!linked.gpuModel){status.textContent='Machine en ligne. Détection du GPU…';return}clearInterval(pairingPollTimer);status.innerHTML='Votre machine est connectée et le GPU est détecté. <a class="button" href="machines.html">Voir ma machine</a>'}catch(error){status.textContent=error.status===401?'Session expirée. Reconnectez-vous.':'Vérification temporairement impossible…'}};await poll();pairingPollTimer=setInterval(poll,5000)}
function startLinkCodeCountdown(output,seconds){clearInterval(linkCodeTimer);const expiresAt=Date.now()+seconds*1000;const render=()=>{const remaining=Math.max(0,Math.ceil((expiresAt-Date.now())/1000));const node=output.querySelector('[data-code-countdown]');if(!node)return clearInterval(linkCodeTimer);if(!remaining){clearInterval(linkCodeTimer);output.querySelector('.link-code-box')?.classList.add('expired');node.textContent='Ce code a expiré.';const copy=output.querySelector('[data-copy-link-code]');if(copy)copy.disabled=true;return}node.textContent=`Ce code expire dans ${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}.`};render();linkCodeTimer=setInterval(render,1000)}
async function createLinkCode(button){
 const output=document.querySelector('[data-link-result]');
 button.disabled=true;
 button.textContent='Création du code…';
 try{
  const baseline=new Set((await request('/machines/mine')).map(machine=>machine.id));
  const data=await request('/machines/link-code',{method:'POST',body:'{}'});
  const code=escapeHTML(data.code);
  output.innerHTML=`<div class="link-code-box"><strong>${code}</strong><button class="button" type="button" data-copy-link-code>Copier le code</button></div><p class="muted" data-code-countdown></p><p class="muted">Code à usage unique. Saisissez-le dans GPUbnb Host.</p><button class="button button-primary" type="button" data-start-pairing>J’ai saisi le code dans GPUbnb Host</button><button class="button" type="button" data-regenerate-code>Générer un nouveau code</button><div data-pairing-status role="status"></div>`;
  output.querySelector('[data-copy-link-code]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(data.code);toast('Code copié.')}catch{toast('Copie impossible : sélectionnez le code manuellement.',true)}});
  output.querySelector('[data-regenerate-code]')?.addEventListener('click',()=>createLinkCode(button));
  output.querySelector('[data-start-pairing]')?.addEventListener('click',event=>{event.currentTarget.disabled=true;pollPairing(output,baseline,Number(data.expiresIn)||600)});
  startLinkCodeCountdown(output,Math.min(Number(data.expiresIn)||0,600));
  toast('Code de liaison créé.');
 }catch(e){
  if(e.status===401){output.innerHTML=`<p class="muted">Connectez-vous avant de créer un code de liaison.</p><a class="button button-primary" href="${authHref()}">Se connecter</a>`;return}
  if(e.code==='provider_role_required'){output.innerHTML='<p class="muted">Activez le rôle propriétaire dans votre profil, puis revenez créer le code.</p><a class="button button-primary" href="onboarding.html?next=host-install.html">Activer mon espace propriétaire</a>';return}
  output.textContent=e.message||'Impossible de créer le code de liaison.';toast(e.message,true);
 }finally{button.disabled=false;button.textContent='Générer un nouveau code'}
}
document.addEventListener('DOMContentLoaded',async()=>{if(!await shell())return;document.querySelector('[data-dashboard]')&&dashboard();document.querySelector('[data-machines]')&&machines();document.querySelector('[data-listings]')&&listings();document.querySelector('[data-bookings]')&&bookings();document.querySelector('[data-create-link]')?.addEventListener('click',e=>createLinkCode(e.currentTarget));document.querySelector('[data-check-machines]')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await machines();toast('État des machines actualisé.')}finally{e.currentTarget.disabled=false}})});window.addEventListener('pagehide',()=>{clearInterval(linkCodeTimer);clearInterval(pairingPollTimer)});
