'use strict';
const API=(window.GPUBNB_API_URL||'').replace(/\/$/,'');
const labels={provider_role_required:"Activez d’abord l’espace propriétaire dans votre profil.",invalid_or_expired_link_code:"Ce code a expiré. Créez-en un nouveau.",internal_error:"Le service rencontre un problème. Réessayez plus tard.",unauthorized:"Connectez-vous pour continuer."};
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
async function request(path,options={}){const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined&&!('content-type' in headers)&&!('Content-Type' in headers))headers['content-type']='application/json';const response=await fetch(`${API}${path}`,{credentials:'include',...options,headers});const data=await response.json().catch(()=>({}));if(!response.ok){const code=data.error||`HTTP ${response.status}`;const error=new Error(labels[code]||code.replaceAll('_',' '));error.status=response.status;error.code=code;throw error}return data}
function toast(message,error=false){document.querySelector('.toast')?.remove();const node=document.createElement('div');node.className=`toast${error?' error':''}`;node.role='status';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),5000)}
function shell(){const current=location.pathname.split('/').pop()||'index.html';document.body.insertAdjacentHTML('afterbegin',`<header class="portal-header"><a class="portal-brand" href="index.html">GPUbnb</a><button class="button mobile-toggle" type="button" aria-expanded="false" aria-controls="portalNav">Menu</button><nav class="portal-nav" id="portalNav" aria-label="Navigation du compte"><a href="dashboard.html">Vue générale</a><a href="machines.html">Mes machines</a><a href="listings.html">Mes annonces</a><a href="bookings.html">Mes réservations</a><a href="demandes.html">Mes demandes</a><a href="revenues.html">Revenus</a><a href="host-install.html">Installer Host</a></nav><a class="button" href="index.html">Marketplace</a></header>`);document.querySelectorAll('.portal-nav a').forEach(a=>{if(a.getAttribute('href')===current)a.setAttribute('aria-current','page')});const toggle=document.querySelector('.mobile-toggle');toggle.addEventListener('click',()=>{const nav=document.querySelector('#portalNav');const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open))});document.body.insertAdjacentHTML('beforeend','<footer class="footer">GPUbnb <span data-version>v1.2</span> · <span data-env>Devnet</span> · préversion de test</footer>')}
function empty(container,title,description,href,label){container.innerHTML=`<div class="empty-state"><span class="badge warn">Information</span><h2>${escapeHTML(title)}</h2><p class="muted">${escapeHTML(description)}</p>${href?`<a class="button button-primary" href="${escapeHTML(href)}">${escapeHTML(label)}</a>`:''}</div>`}
function authHref(){const current=location.pathname.split('/').pop()||'dashboard.html';return `auth.html?next=${encodeURIComponent(current)}`}
function errorState(root,title,error){const unauthorized=error?.status===401;empty(root,unauthorized?'Connexion nécessaire':title,unauthorized?'Connectez-vous pour continuer.':(error?.message||'Le service est temporairement indisponible.'),unauthorized?authHref():null,unauthorized?'Se connecter':null)}
function nextStep(data){if(!data.user.canHost)return ['Activer l’espace propriétaire','Activez le rôle propriétaire pour connecter une machine.','onboarding.html'];if(!data.host.machines.length)return ['Installer GPUbnb Host','Téléchargez l’application puis créez un code de liaison.','host-install.html'];if(!data.host.listings.length)return ['Publier une annonce','Votre machine est reliée. Définissez maintenant son offre.','publish.html'];if(data.tenant.bookings.length)return ['Suivre votre réservation','Consultez son état et les étapes de paiement.','bookings.html'];return ['Rechercher un GPU','Comparez les GPU disponibles sur la marketplace.','index.html#market']}
async function dashboard(){const root=document.querySelector('[data-dashboard]');try{const data=await request('/dashboard');document.querySelector('[data-name]').textContent=data.user.pseudonym;const [title,text,href]=nextStep(data);document.querySelector('[data-next-title]').textContent=title;document.querySelector('[data-next-text]').textContent=text;document.querySelector('[data-next-link]').href=href;document.querySelector('[data-next-link]').textContent=title;document.querySelector('[data-machine-count]').textContent=data.host.machines.length;document.querySelector('[data-listing-count]').textContent=data.host.listings.length;document.querySelector('[data-booking-count]').textContent=data.tenant.bookings.length;document.querySelector('[data-role]').textContent=data.user.canHost?'Locataire + propriétaire':'Locataire';document.querySelectorAll('[data-host-only]').forEach(x=>x.hidden=!data.user.canHost)}catch(e){toast(e.message,true);errorState(root,'Tableau de bord indisponible',e)}}
async function machines(){const root=document.querySelector('[data-machines]');try{const rows=await request('/machines/mine');if(!rows.length)return empty(root,'Aucune machine reliée','Installez GPUbnb Host, puis créez un code de liaison.','host-install.html','Installer GPUbnb Host');root.innerHTML=rows.map(x=>`<article class="list-row"><div><strong>${escapeHTML(x.gpuModel||'GPU en détection')}</strong><div class="muted">${x.vramMiB?`${escapeHTML(x.vramMiB)} MiB VRAM · `:''}${x.lastHeartbeatAt?'Dernier signal '+new Date(x.lastHeartbeatAt).toLocaleString('fr-FR'):'Aucun signal reçu'}</div></div><span class="badge ${x.connectivity==='ONLINE'?'ok':'warn'}">${x.connectivity==='ONLINE'?'Fonctionnel':'Hors ligne'}</span></article>`).join('')}catch(e){errorState(root,'Machines indisponibles',e)}}
async function listings(){const root=document.querySelector('[data-listings]');try{const data=await request('/dashboard');const rows=data.host.listings||[];if(!rows.length)return empty(root,'Aucune annonce publiée','Reliez une machine puis créez votre première offre.','publish.html','Publier une annonce');root.innerHTML=rows.map(x=>`<article class="list-row"><div><strong>${escapeHTML(x.title)}</strong><div class="muted">Créée le ${new Date(x.createdAt).toLocaleDateString('fr-FR')} · ${escapeHTML(x.hourlyLamports)} lamports/heure</div></div><span class="badge ${x.status==='ACTIVE'?'ok':'warn'}">${escapeHTML(x.status)}</span></article>`).join('')}catch(e){errorState(root,'Annonces indisponibles',e)}}
async function bookings(){const root=document.querySelector('[data-bookings]');try{const data=await request('/dashboard');const rows=data.tenant.bookings||[];if(!rows.length)return empty(root,'Aucune réservation','Choisissez un GPU disponible pour démarrer un test réel.','index.html#market','Explorer la marketplace');root.innerHTML=rows.map(x=>`<article class="list-row"><div><strong>${escapeHTML(x.listing?.title||'Réservation GPU')}</strong><div class="muted">${new Date(x.startsAt).toLocaleString('fr-FR')} → ${new Date(x.endsAt).toLocaleString('fr-FR')} · ${escapeHTML(x.quotedLamports)} lamports</div></div><span class="badge ${['ACTIVE','SETTLED','FUNDED'].includes(x.status)?'ok':'warn'}">${escapeHTML(x.status)}</span></article>`).join('')}catch(e){errorState(root,'Réservations indisponibles',e)}}
async function createLinkCode(button){
 const output=document.querySelector('[data-link-result]');
 button.disabled=true;
 try{
  const data=await request('/machines/link-code',{method:'POST',body:'{}'});
  const code=escapeHTML(data.code);
  output.innerHTML=`<div class="link-code-box"><strong>${code}</strong><button class="button" type="button" data-copy-link-code>Copier</button></div><p class="muted">Valable ${Math.round(data.expiresIn/60)} minutes. Collez ce code dans GPUbnb Host pour relier automatiquement votre GPU au site.</p>`;
  output.querySelector('[data-copy-link-code]')?.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(data.code);toast('Code copié.')}catch{toast('Copie impossible : sélectionnez le code manuellement.',true)}});
  toast('Code de liaison créé.');
 }catch(e){
  if(e.status===401){output.innerHTML=`<p class="muted">Connectez-vous avant de créer un code de liaison.</p><a class="button button-primary" href="${authHref()}">Se connecter</a>`;return}
  if(e.code==='provider_role_required'){output.innerHTML='<p class="muted">Activez le rôle propriétaire dans votre profil, puis revenez créer le code.</p><a class="button button-primary" href="onboarding.html?next=host-install.html">Activer mon espace propriétaire</a>';return}
  output.textContent=e.message||'Impossible de créer le code de liaison.';toast(e.message,true);
 }finally{button.disabled=false}
}
document.addEventListener('DOMContentLoaded',()=>{shell();document.querySelector('[data-dashboard]')&&dashboard();document.querySelector('[data-machines]')&&machines();document.querySelector('[data-listings]')&&listings();document.querySelector('[data-bookings]')&&bookings();document.querySelector('[data-create-link]')?.addEventListener('click',e=>createLinkCode(e.currentTarget));document.querySelector('[data-check-machines]')?.addEventListener('click',async e=>{e.currentTarget.disabled=true;try{await machines();toast('État des machines actualisé.')}finally{e.currentTarget.disabled=false}})});
