'use strict';
const API=(window.GPUBNB_CONFIG?.apiBase||'').replace(/\/$/,'');
const form=document.querySelector('#publishForm');
const message=document.querySelector('#formMessage');
const description=form.elements.description;
const descriptionCount=document.querySelector('#descriptionCount');
const machineSelect=form.elements.machineId;
const submitButton=document.querySelector('#publishSubmit');
const machineState=document.querySelector('#machineState');
let machinesById=new Map();
async function api(path,options={}){const headers={accept:'application/json',...(options.headers||{})};if(options.body!==undefined&&!('content-type' in headers)&&!('Content-Type' in headers))headers['content-type']='application/json';const r=await fetch(`${API}${path}`,{credentials:'include',...options,headers});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||`HTTP ${r.status}`);e.status=r.status;e.payload=data;throw e}return data;}
function show(text,error=false){message.textContent=text;message.className=`form-message ${error?'error':'success'}`}
function value(name){return String(form.elements[name].value||'').trim()}
function setPublishReady(ready){submitButton.disabled=!ready;machineSelect.disabled=!machinesById.size}
function stateLabel(machine){const state=machine.state?.state||'UNKNOWN';const action=machine.state?.nextAction?` · Action : ${machine.state.nextAction}`:'';return `${state}${action}`}
function describeMachine(machine){const status=machine.connectivity==='ONLINE'?'En ligne':'Hors ligne';const verified=machine.verifiedAt?'Vérifiée':'En attente de vérification';const publishable=machine.state?.canPublish?'Prête à publier':'Non publiable';return `${machine.gpuModel||'GPU en détection'} · ${status} · ${verified} · ${publishable}`}
function refreshSelectedMachineState(){const machine=machinesById.get(machineSelect.value);if(!machine){machineState.textContent=machinesById.size?'Choisissez une machine prête à publier.':'Aucune machine reliée.';setPublishReady(false);return}const canPublish=Boolean(machine.state?.canPublish);machineState.textContent=canPublish?`Machine prête : ${stateLabel(machine)}`:`Machine bloquée : ${stateLabel(machine)}${machine.state?.blockingReason?` · ${machine.state.blockingReason}`:''}`;setPublishReady(canPublish)}
async function loadAccount(){setPublishReady(false);try{const me=await api('/auth/me');document.querySelector('#accountState').textContent=`Connecté : ${me.user.pseudonym}`;if(!me.user.canHost){machineState.textContent='Activez le rôle propriétaire avant de publier.';show('Le rôle propriétaire est requis.',true);return}const machines=await api('/machines/mine');machinesById=new Map(machines.map(machine=>[machine.id,machine]));machineSelect.replaceChildren();if(!machines.length){machineSelect.add(new Option('Aucune machine reliée',''));machineState.textContent='Aucune machine reliée. Installez GPUbnb Host puis créez un code de liaison.';show('Reliez d’abord une machine avec GPUbnb Host.',true);return}machineSelect.add(new Option('Choisir une machine prête à publier',''));for(const m of machines){machineSelect.add(new Option(describeMachine(m),m.id));}const readyCount=machines.filter(m=>m.state?.canPublish).length;machineState.textContent=`${readyCount}/${machines.length} machine${machines.length>1?'s':''} prête${readyCount>1?'s':''} à publier.`;setPublishReady(false);}catch(e){if(e.status===401){location.href='/auth.html?next=publish';return}machineSelect.replaceChildren(new Option('Machines indisponibles',''));machinesById=new Map();machineState.textContent='Impossible de charger les machines.';show('Impossible de charger le compte ou les machines.',true)}}
description.addEventListener('input',()=>{descriptionCount.value=String(description.value.length)});
machineSelect.addEventListener('change',refreshSelectedMachineState);
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;const selected=machinesById.get(machineSelect.value);if(!selected){show('Choisissez une machine reliée.',true);return}if(!selected.state?.canPublish){show(`Machine non prête : ${selected.state?.blockingReason||selected.state?.state||'état inconnu'}`,true);return}submitButton.disabled=true;try{show('Publication en cours…');const listing=await api('/listings',{method:'POST',body:JSON.stringify({machineId:machineSelect.value,title:value('title'),description:value('description'),hourlySol:Number(form.elements.hourlySol.value)})});show(listing.status==='ACTIVE'?'Annonce publiée et visible.':'Annonce créée en attente de vérification GPU.');form.reset();descriptionCount.value='0';await loadAccount();}catch(e){show(e.message||'Publication impossible',true);submitButton.disabled=false}});
document.querySelector('#resetForm').addEventListener('click',()=>{form.reset();descriptionCount.value='0';message.textContent='';refreshSelectedMachineState()});
loadAccount();
