'use strict';
const API=(window.GPUBNB_CONFIG?.apiBase||window.GPUBNB_API_URL||'').replace(/\/$/,'');
const sessionId=new URLSearchParams(location.search).get('id');
const terminalStatuses=['COMPLETED','FAILED','CANCELLED','TIMED_OUT','QUARANTINED'];
async function sessionApi(path,options={}){const response=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json'},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`Erreur API (${response.status})`);error.status=response.status;throw error}return data}
const text=(id,value)=>{const node=document.querySelector(`#${id}`);if(node)node.textContent=value};
function displayMetric(value,suffix){return Number.isFinite(value)?`${Math.round(value)}${suffix}`:'—'}
function render(session){const metric=session.metrics?.[0];const limits=session.resourceLimits||{};const progress=Math.max(0,Math.min(100,Number(session.preparationProgress)||0));text('sessionTitle',session.machineWorkspace?.workspace?.name||'Compute');text('sessionStatus',session.status);text('sessionSummary',`Session ${session.id} · contrôlée par GPUbnb Agent`);text('preparationStep',String(session.preparationStep||'EN ATTENTE').replaceAll('_',' '));text('preparationPercent',`${progress} %`);document.querySelector('#preparationBar').style.width=`${progress}%`;document.querySelector('.progress-track').setAttribute('aria-valuenow',String(progress));text('preparationMessage',session.status==='READY'?'Votre environnement a réussi tous les contrôles et vous attend.':session.status==='FAILED'?'La préparation a échoué. Aucune durée inutilisable ne sera facturée.':'GPUbnb prépare automatiquement l’image, l’isolation et le contrôle de santé.');text('gpuMetric',displayMetric(metric?.gpuUtilization,'%'));text('vramMetric',displayMetric(metric?.memoryUsedMiB,' MiB'));text('tempMetric',displayMetric(metric?.temperatureC,' °C'));text('cpuMetric',displayMetric(metric?.cpuUtilization,'%'));text('ramMetric',displayMetric(metric?.ramUsedMiB,' MiB'));text('usageMetric',`${session.booking?.validSeconds||0} / ${session.booking?.expectedSeconds||0} s`);text('isolationValue',session.isolationType||'—');text('networkValue',limits.networkAccess||'—');text('memoryLimitValue',limits.maxRamMiB?`${limits.maxRamMiB} MiB`:'—');text('expiresValue',new Date(session.expiresAt).toLocaleString('fr-FR'));document.querySelector('#startSession').disabled=session.status!=='READY';document.querySelector('#stopSession').disabled=terminalStatuses.includes(session.status)||session.status==='STOP_REQUESTED'}
async function refresh(){if(!sessionId){text('sessionMessage','Identifiant de session absent.');return}try{render(await sessionApi(`/workspace-sessions/${encodeURIComponent(sessionId)}`))}catch(error){if(error.status===401)location.href=`auth.html?next=${encodeURIComponent(`session.html?id=${sessionId}`)}`;else text('sessionMessage',error.message)}}
document.querySelector('#startSession').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await sessionApi(`/workspace-sessions/${encodeURIComponent(sessionId)}/start`,{method:'POST',body:'{}'});await refresh()}catch(error){text('sessionMessage',error.message);event.currentTarget.disabled=false}});
document.querySelector('#stopSession').addEventListener('click',async event=>{event.currentTarget.disabled=true;try{await sessionApi(`/workspace-sessions/${encodeURIComponent(sessionId)}/stop`,{method:'POST',body:'{}'});text('sessionMessage','Arrêt demandé. GPUbnb Agent va nettoyer l’environnement.');await refresh()}catch(error){text('sessionMessage',error.message);event.currentTarget.disabled=false}});
refresh();setInterval(refresh,10000);
