'use strict';
const API=(window.GPUBNB_CONFIG?.apiBase||window.GPUBNB_API_URL||'').replace(/\/$/,'');
const grid=document.querySelector('#workspaceGrid');const machineId=new URLSearchParams(location.search).get('machine');let catalogue=[];let analyses=new Map();let activeFilter='ALL';
async function api(path,options={}){const response=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json'},...options});const data=response.status===204?{}:await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Erreur API (${response.status})`);return data}
const releaseLabel=value=>({BETA:'Bêta',UPCOMING:'Bientôt disponible',EXPERIMENTAL:'Expérimental',SUSPENDED:'Suspendu'}[value]||value);
const licenseLabel=value=>({INCLUDED_OPEN_SOURCE:'Logiciels libres inclus',USER_ACCOUNT_REQUIRED:'Compte personnel requis',USER_LICENSE_REQUIRED:'Licence utilisateur requise',MIXED:'Licences selon les outils'}[value]||'Licence à vérifier');
function visible(item){if(activeFilter==='ALL')return true;if(activeFilter==='AVAILABLE')return item.release==='BETA'&&['READY','LIMITED'].includes(item.analysis?.state);return item.category===activeFilter||(activeFilter==='CREATION'&&['CREATION','VIDEO','CAD','AUDIO'].includes(item.category))||(activeFilter==='GAMING'&&item.category==='GAMING')}
function render(){grid.replaceChildren();const items=catalogue.filter(visible);document.querySelector('#resultCount').textContent=`${items.length} espace${items.length>1?'s':''} affiché${items.length>1?'s':''}`;for(const item of items){const record=analyses.get(item.slug);const analysis=record?.analysis;const card=document.createElement('article');card.className='workspace-card';card.dataset.release=item.release;card.dataset.category=item.category;const compatible=item.release==='BETA'&&['compute','developer'].includes(item.slug)&&['READY','LIMITED'].includes(record?.state);const score=analysis?record.compatibilityScore:0;const releaseClass=item.release==='UPCOMING'?'upcoming':item.release==='EXPERIMENTAL'?'experimental':'';card.innerHTML=`<div class="card-top"><span class="icon-wrap"><span class="icon" aria-hidden="true">${item.icon}</span></span><span class="release ${releaseClass}">${releaseLabel(item.release)}</span></div><h2>${item.name}</h2><p class="summary">${item.summary}</p><div class="tech-list">${item.technologies.slice(0,4).map(tech=>`<span>${tech}</span>`).join('')}</div><div class="card-meta"><div class="score-row"><span>Compatibilité</span><strong>${analysis?`${score} %`:'À analyser'}</strong></div><div class="score-track" style="--score:${score}%"><span></span></div><p class="reason">${analysis?(analysis.missing[0]||analysis.reasons[0]||'Capacités vérifiées'):'Connectez une machine pour obtenir son score.'}</p><span class="license">${licenseLabel(item.license)}</span></div>`;const button=document.createElement('button');button.type='button';button.disabled=true;button.textContent=compatible?'Proposé automatiquement aux locataires':item.release==='BETA'?'Analyse ou configuration nécessaire':releaseLabel(item.release);card.append(button);grid.append(card)}if(!items.length)grid.innerHTML='<p class="loading">Aucun espace ne correspond à ce filtre.</p>'}
async function toggle(item,record,button){button.disabled=true;try{if(item.slug==='developer'){await api(`/machines/${machineId}/workspaces/developer/enable-beta`,{method:'POST',body:'{}'})}else{await api(`/machines/${machineId}/workspaces/${item.slug}`,{method:'PATCH',body:JSON.stringify({enabled:!record.enabledByOwner})})}await loadOwner()}catch(error){document.querySelector('#ownerMessage').textContent=error.message;button.disabled=false}}
async function loadOwner(){try{const machine=await api(`/machines/${machineId}/workspaces/manage`);analyses=new Map(machine.workspaces.map(row=>[row.workspace.slug,row]));render()}catch(error){document.querySelector('#ownerMessage').textContent=error.message}}
async function analyze(){const button=document.querySelector('#analyzeButton');button.disabled=true;document.querySelector('#ownerMessage').textContent='Analyse en cours…';try{await api(`/machines/${machineId}/workspaces/analyze`,{method:'POST',body:'{}'});document.querySelector('#ownerMessage').textContent='Analyse terminée.';await loadOwner()}catch(error){document.querySelector('#ownerMessage').textContent=error.message}finally{button.disabled=false}}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;render()}));
(async()=>{try{catalogue=(await api('/workspaces')).workspaces;if(machineId){document.querySelector('#ownerTools').hidden=false;document.querySelector('#ownerTools').style.display='flex';document.querySelector('#analyzeButton').addEventListener('click',analyze);await loadOwner()}render()}catch(error){grid.textContent=`Impossible de charger les espaces : ${error.message}`}})();
