'use strict';
const API=(window.GPUBNB_CONFIG?.apiBase||window.GPUBNB_API_URL||'').replace(/\/$/,'');
const grid=document.querySelector('#workspaceGrid');const machineId=new URLSearchParams(location.search).get('machine');let catalogue=[];let analyses=new Map();let activeFilter='ALL';
async function api(path,options={}){const response=await fetch(`${API}${path}`,{credentials:'include',headers:{'content-type':'application/json'},...options});const data=response.status===204?{}:await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Erreur API (${response.status})`);return data}
const releaseLabel=value=>({BETA:'Bêta',UPCOMING:'Bientôt disponible',EXPERIMENTAL:'Expérimental',SUSPENDED:'Suspendu'}[value]||value);
function visible(item){if(activeFilter==='ALL')return true;if(activeFilter==='AVAILABLE')return item.release==='BETA'&&item.analysis?.enabledByOwner;return item.category===activeFilter||(activeFilter==='CREATION'&&['CREATION','VIDEO','CAD','AUDIO'].includes(item.category))||(activeFilter==='GAMING'&&item.category==='GAMING')}
function render(){grid.replaceChildren();for(const item of catalogue.filter(visible)){const record=analyses.get(item.slug);const analysis=record?.analysis;const card=document.createElement('article');card.className='workspace-card';card.dataset.release=item.release;const available=item.release==='BETA'&&record?.enabledByOwner;const canOwnerEnable=machineId&&item.slug==='compute'&&item.release==='BETA'&&['READY','LIMITED'].includes(record?.state);card.innerHTML=`<div class="card-top"><span class="icon" aria-hidden="true">${item.icon}</span><span class="release ${item.release==='UPCOMING'?'upcoming':''}">${releaseLabel(item.release)}</span></div><h2>${item.name}</h2><p class="summary">${item.summary}</p><p class="tech">${item.technologies.slice(0,4).join(' · ')}</p><p class="score">${analysis?`Compatibilité : ${record.compatibilityScore} %`:'Compatibilité à analyser'}</p><p class="reason">${analysis?(analysis.missing[0]||analysis.reasons[0]||'Capacités vérifiées'):'Analyse propriétaire nécessaire'}</p>`;const button=document.createElement('button');button.type='button';if(canOwnerEnable){button.disabled=false;button.textContent=record.enabledByOwner?'Désactiver':'Activer cet espace';button.addEventListener('click',()=>toggle(item,record,button))}else{button.disabled=true;button.textContent=available?'Disponible avec cette machine':item.release==='BETA'?'Analyse ou configuration nécessaire':releaseLabel(item.release)}card.append(button);grid.append(card)}if(!grid.children.length)grid.innerHTML='<p>Aucun espace ne correspond à ce filtre.</p>'}
async function toggle(item,record,button){button.disabled=true;try{await api(`/machines/${machineId}/workspaces/${item.slug}`,{method:'PATCH',body:JSON.stringify({enabled:!record.enabledByOwner})});await loadOwner()}catch(error){document.querySelector('#ownerMessage').textContent=error.message;button.disabled=false}}
async function loadOwner(){try{const machine=await api(`/machines/${machineId}/workspaces/manage`);analyses=new Map(machine.workspaces.map(row=>[row.workspace.slug,row]));render()}catch(error){document.querySelector('#ownerMessage').textContent=error.message}}
async function analyze(){const button=document.querySelector('#analyzeButton');button.disabled=true;document.querySelector('#ownerMessage').textContent='Analyse en cours…';try{await api(`/machines/${machineId}/workspaces/analyze`,{method:'POST',body:'{}'});document.querySelector('#ownerMessage').textContent='Analyse terminée.';await loadOwner()}catch(error){document.querySelector('#ownerMessage').textContent=error.message}finally{button.disabled=false}}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;render()}));
(async()=>{try{catalogue=(await api('/workspaces')).workspaces;if(machineId){document.querySelector('#ownerTools').hidden=false;document.querySelector('#ownerTools').style.display='flex';document.querySelector('#analyzeButton').addEventListener('click',analyze);await loadOwner()}render()}catch(error){grid.textContent=`Impossible de charger les espaces : ${error.message}`}})();
