import Fastify from 'fastify'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit'; import cookie from '@fastify/cookie'; import fastifyStatic from '@fastify/static'; import path from 'node:path';
import { PrismaClient, MachineConnectivity, MachineOperational, ModerationStatus, ListingStatus, BookingStatus, PaymentStatus } from '@prisma/client';
import { Redis } from 'ioredis'; import { z, ZodError } from 'zod'; import bs58 from 'bs58'; import nacl from 'tweetnacl'; import crypto from 'node:crypto';
import { config } from './config.js'; import { createNonce,consumeNonce,issueSession,requireSession,revokeSession,walletKey } from './auth.js'; import { assertTrustedOrigin, constantTimeToken, verifyAgentRequest, recordSecurityFailure } from './security.js'; import {calculateSettlement,bigintJson} from './settlement.js'; import { buildOpenEscrowTransaction, deriveEscrowAddresses, verifyOpenEscrowTransaction } from './solana.js'; import { PublicKey } from '@solana/web3.js';
const app=Fastify({logger:{redact:['req.headers.authorization','req.headers.cookie','req.headers.x-agent-signature','res.headers.set-cookie']},trustProxy:config.TRUST_PROXY==='true',bodyLimit:config.MAX_BODY_BYTES,requestIdHeader:'x-request-id'}); const db=new PrismaClient(); const redis=new Redis(config.REDIS_URL,{maxRetriesPerRequest:2,enableReadyCheck:true});
redis.on('error',(err:Error)=>app.log.error({err},'redis_error'));
await app.register(cookie); await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'"],imgSrc:["'self'",'data:','https:'],connectSrc:["'self'"],objectSrc:["'none'"],baseUri:["'self'"],frameAncestors:["'none'"],formAction:["'self'"]}}}); await app.register(rateLimit,{max:120,timeWindow:'1 minute'});
app.addHook('onRequest',async(req,reply)=>{reply.header('cache-control','no-store');reply.header('x-request-id',req.id);if(!assertTrustedOrigin(req,reply,config.PUBLIC_APP_DOMAIN))return reply;});
app.setErrorHandler((err,req,reply)=>{if(err instanceof ZodError)return reply.code(400).send({error:'invalid_request',issues:err.issues.map(x=>({path:x.path.join('.'),message:x.message}))}); req.log.error(err); return reply.code(500).send({error:'internal_error'});});
app.get('/health',async()=>({ok:true,cluster:config.SOLANA_CLUSTER,mainnetEnabled:config.ALLOW_MAINNET==='true',escrowConfigured:config.ESCROW_PROGRAM_ID!=='NOT_DEPLOYED_YET'}));
app.get('/ready',async(req,reply)=>{try{await db.$queryRaw`SELECT 1`;await redis.ping();return {ok:true}}catch(err){req.log.error(err);return reply.code(503).send({ok:false})}});
app.post('/auth/nonce',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(req)=>{const {wallet}=z.object({wallet:z.string()}).parse(req.body);return createNonce(redis,wallet,config.PUBLIC_APP_DOMAIN)});
app.post('/auth/verify',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(req,reply)=>{const b=z.object({wallet:z.string(),message:z.string().max(1000),signature:z.string().max(200)}).parse(req.body);if(!await consumeNonce(redis,b.wallet,b.message,b.signature))return reply.code(401).send({error:'invalid_or_replayed_signature'});const wallet=walletKey(b.wallet);const user=await db.user.upsert({where:{wallet},update:{lastLoginAt:new Date()},create:{wallet,pseudonym:`user-${crypto.randomBytes(4).toString('hex')}`,lastLoginAt:new Date()}});await issueSession(redis,reply,{userId:user.id,wallet,createdAt:new Date().toISOString()});return {ok:true,user:{id:user.id,pseudonym:user.pseudonym,walletMasked:`${wallet.slice(0,4)}…${wallet.slice(-4)}`}}});
app.post('/auth/logout',async(req,reply)=>{const token=req.cookies[config.SESSION_COOKIE_NAME];if(token)await revokeSession(redis,token);reply.clearCookie(config.SESSION_COOKIE_NAME,{path:'/'});return {ok:true}});
const heartbeatSchema=z.object({machineId:z.string().cuid(),counter:z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER),challenge:z.string().min(16).max(200),timestamp:z.string().datetime(),gpuUuid:z.string().min(5).max(200),gpuModel:z.string().min(2).max(200),vramMiB:z.number().int().positive().max(1_000_000),driverVersion:z.string().max(100),gpuUtilization:z.number().int().min(0).max(100),memoryUsedMiB:z.number().int().min(0),temperatureC:z.number().int().min(-20).max(130),cudaProbeOk:z.boolean(),sessionId:z.string().cuid().nullable(),signature:z.string().max(200)});
app.get('/agent/challenge/:machineId',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const {machineId}=z.object({machineId:z.string().cuid()}).parse(req.params);const m=await db.machine.findUnique({where:{id:machineId},select:{id:true,agentPublicKey:true,moderationStatus:true}});if(!m)return reply.code(404).send({error:'unknown_machine'});if(m.moderationStatus!==ModerationStatus.CLEAR)return reply.code(403).send({error:'machine_quarantined'});if(!await verifyAgentRequest(redis,machineId,m.agentPublicKey,'GET',`/agent/challenge/${machineId}`,req.headers['x-agent-timestamp'],req.headers['x-agent-signature'])){await recordSecurityFailure(redis,`agent:${machineId}`);return reply.code(401).send({error:'invalid_agent_request'});}const challenge=crypto.randomBytes(24).toString('base64url');await redis.set(`agent-challenge:${machineId}:${challenge}`,'1','EX',60,'NX');return {challenge,expiresIn:60}});
app.post('/agent/heartbeat',{config:{rateLimit:{max:30,timeWindow:'1 minute'}}},async(req,reply)=>{const b=heartbeatSchema.parse(req.body);const m=await db.machine.findUnique({where:{id:b.machineId}});if(!m)return reply.code(404).send({error:'unknown_machine'});const age=Math.abs(Date.now()-Date.parse(b.timestamp));if(age>config.HEARTBEAT_MAX_AGE_SECONDS*1000)return reply.code(409).send({error:'stale_heartbeat'});if(!await redis.getdel(`agent-challenge:${b.machineId}:${b.challenge}`))return reply.code(409).send({error:'invalid_or_replayed_challenge'});if(BigInt(b.counter)<=m.lastCounter)return reply.code(409).send({error:'counter_replay'});const canonical=[b.machineId,b.counter,b.challenge,b.timestamp,b.gpuUuid,b.gpuModel,b.vramMiB,b.driverVersion,b.gpuUtilization,b.memoryUsedMiB,b.temperatureC,b.cudaProbeOk,b.sessionId??''].join('|');let verified=false;try{verified=nacl.sign.detached.verify(new TextEncoder().encode(canonical),bs58.decode(b.signature),bs58.decode(m.agentPublicKey))}catch{}if(!verified){const quarantine=await recordSecurityFailure(redis,`agent:${b.machineId}`);if(quarantine)await db.machine.update({where:{id:b.machineId},data:{moderationStatus:ModerationStatus.QUARANTINED,connectivity:MachineConnectivity.OFFLINE,operational:MachineOperational.UNAVAILABLE}});return reply.code(401).send({error:'invalid_agent_signature'});}
 if(b.memoryUsedMiB>b.vramMiB||(!b.cudaProbeOk&&b.gpuUtilization>10)){await recordSecurityFailure(redis,`telemetry:${b.machineId}`,4);return reply.code(409).send({error:'incoherent_telemetry'});}
 if(b.sessionId){const active=await db.booking.findFirst({where:{id:b.sessionId,listing:{machineId:m.id},status:{in:[BookingStatus.FUNDED,BookingStatus.STARTING,BookingStatus.ACTIVE,BookingStatus.DEGRADED]},startsAt:{lte:new Date(Date.now()+5*60_000)},endsAt:{gte:new Date(Date.now()-5*60_000)}}});if(!active)return reply.code(409).send({error:'invalid_session_binding'});}
 const sameGpu=!m.gpuUuid||m.gpuUuid===b.gpuUuid;const canPublish=m.moderationStatus===ModerationStatus.CLEAR&&sameGpu&&b.cudaProbeOk;await db.$transaction(async tx=>{await tx.machine.update({where:{id:m.id},data:{connectivity:MachineConnectivity.ONLINE,operational:b.sessionId?MachineOperational.RUNNING:MachineOperational.AVAILABLE,lastHeartbeatAt:new Date(),lastCounter:BigInt(b.counter),gpuUuid:b.gpuUuid,gpuModel:b.gpuModel,vramMiB:b.vramMiB,driverVersion:b.driverVersion,lastCudaProbeOk:b.cudaProbeOk,verifiedAt:sameGpu&&b.cudaProbeOk?new Date():m.verifiedAt}});await tx.heartbeat.create({data:{machineId:m.id,counter:BigInt(b.counter),agentTimestamp:new Date(b.timestamp),gpuUtilization:b.gpuUtilization,memoryUsedMiB:b.memoryUsedMiB,temperatureC:b.temperatureC,cudaProbeOk:b.cudaProbeOk,sessionId:b.sessionId,signatureHash:crypto.createHash('sha256').update(b.signature).digest('hex')}});if(canPublish)await tx.gpuListing.updateMany({where:{machineId:m.id,status:ListingStatus.HIDDEN_OFFLINE},data:{status:ListingStatus.ACTIVE}})});return {ok:true,publishable:canPublish};});
app.get('/listings',async()=>{const rows=await db.gpuListing.findMany({where:{status:ListingStatus.ACTIVE,machine:{connectivity:MachineConnectivity.ONLINE,moderationStatus:ModerationStatus.CLEAR,lastCudaProbeOk:true,lastHeartbeatAt:{gte:new Date(Date.now()-config.HEARTBEAT_OFFLINE_SECONDS*1000)}}},select:{id:true,title:true,description:true,hourlyLamports:true,createdAt:true,machine:{select:{gpuModel:true,vramMiB:true,verifiedAt:true}},owner:{select:{pseudonym:true,profile:{select:{reliabilityScore:true,completedSessions:true}}}}},take:100,orderBy:{createdAt:'desc'}});return rows.map(r=>({...r,hourlyLamports:bigintJson(r.hourlyLamports)}))});
app.post('/bookings',async(req,reply)=>{const s=await requireSession(req,reply,redis);if(!s)return;const b=z.object({listingId:z.string().cuid(),startsAt:z.string().datetime(),endsAt:z.string().datetime(),idempotencyKey:z.string().uuid()}).parse(req.body);const start=new Date(b.startsAt),end=new Date(b.endsAt);if(start.getTime()<Date.now()-60_000||start.getTime()>Date.now()+30*24*3600_000||end<=start||end.getTime()-start.getTime()>24*3600_000)return reply.code(400).send({error:'invalid_period'});const booking=await db.$transaction(async tx=>{const existing=await tx.booking.findUnique({where:{buyerId_idempotencyKey:{buyerId:s.userId,idempotencyKey:b.idempotencyKey}}});if(existing)return existing;const listing=await tx.gpuListing.findFirst({where:{id:b.listingId,status:ListingStatus.ACTIVE,machine:{connectivity:MachineConnectivity.ONLINE,lastCudaProbeOk:true}},select:{id:true,hourlyLamports:true,ownerId:true}});if(!listing||listing.ownerId===s.userId)throw new Error('listing_unavailable');const overlap=await tx.booking.count({where:{listingId:listing.id,status:{in:[BookingStatus.AWAITING_DEPOSIT,BookingStatus.FUNDED,BookingStatus.STARTING,BookingStatus.ACTIVE]},startsAt:{lt:end},endsAt:{gt:start}}});if(overlap)throw new Error('time_slot_unavailable');const expected=Math.ceil((end.getTime()-start.getTime())/1000);const quote=listing.hourlyLamports*BigInt(expected)/3600n;if(quote<=0n)throw new Error('quote_too_small');return tx.booking.create({data:{buyerId:s.userId,listingId:listing.id,startsAt:start,endsAt:end,quotedLamports:quote,expectedSeconds:expected,idempotencyKey:b.idempotencyKey,status:BookingStatus.AWAITING_DEPOSIT}})}).catch(e=>{const msg=e instanceof Error?e.message:'booking_failed';return reply.code(409).send({error:msg})});if(!('id'in booking))return booking;return {...booking,quotedLamports:bigintJson(booking.quotedLamports)}});

app.post('/bookings/:id/payment-intent',async(req,reply)=>{const s=await requireSession(req,reply,redis);if(!s)return; if(config.ESCROW_PROGRAM_ID==='NOT_DEPLOYED_YET')return reply.code(503).send({error:'escrow_not_deployed'}); const {id}=z.object({id:z.string().cuid()}).parse(req.params); const b=await db.booking.findFirst({where:{id,buyerId:s.userId,status:BookingStatus.AWAITING_DEPOSIT},include:{buyer:true,listing:{include:{owner:true}}}}); if(!b)return reply.code(404).send({error:'booking_not_found'}); const programId=new PublicKey(config.ESCROW_PROGRAM_ID); const buyer=new PublicKey(b.buyer.wallet); const provider=new PublicKey(b.listing.owner.wallet); const expiresAtUnix=BigInt(Math.floor(b.startsAt.getTime()/1000)+900); const built=await buildOpenEscrowTransaction({rpcUrl:config.SOLANA_RPC_URL,commitment:config.SOLANA_COMMITMENT,programId,buyer,provider,bookingId:b.id,amount:b.quotedLamports,expectedSeconds:b.expectedSeconds,expiresAtUnix}); await db.booking.update({where:{id:b.id},data:{escrowAddress:built.escrow.toBase58()}}); return {transactionBase64:built.transactionBase64,escrowAddress:built.escrow.toBase58(),programId:programId.toBase58(),amountLamports:b.quotedLamports.toString(),cluster:config.SOLANA_CLUSTER};});
app.post('/bookings/:id/confirm-deposit',async(req,reply)=>{const s=await requireSession(req,reply,redis);if(!s)return; if(config.ESCROW_PROGRAM_ID==='NOT_DEPLOYED_YET')return reply.code(503).send({error:'escrow_not_deployed'}); const {id}=z.object({id:z.string().cuid()}).parse(req.params); const {signature}=z.object({signature:z.string().min(64).max(100)}).parse(req.body); const b=await db.booking.findFirst({where:{id,buyerId:s.userId},include:{buyer:true,listing:{include:{owner:true}}}}); if(!b)return reply.code(404).send({error:'booking_not_found'}); if(b.depositSignature&&b.depositSignature!==signature)return reply.code(409).send({error:'deposit_already_recorded'}); const programId=new PublicKey(config.ESCROW_PROGRAM_ID); const {escrow}=deriveEscrowAddresses(programId,b.id); const ok=await verifyOpenEscrowTransaction({rpcUrl:config.SOLANA_RPC_URL,commitment:config.SOLANA_COMMITMENT,programId,signature,buyer:new PublicKey(b.buyer.wallet),provider:new PublicKey(b.listing.owner.wallet),amount:b.quotedLamports,expectedSeconds:b.expectedSeconds,escrow}); if(!ok)return reply.code(409).send({error:'invalid_deposit_transaction'}); await db.$transaction([db.booking.update({where:{id:b.id},data:{status:BookingStatus.FUNDED,escrowAddress:escrow.toBase58(),depositSignature:signature}}),db.payment.upsert({where:{bookingId:b.id},update:{grossLamports:b.quotedLamports,status:PaymentStatus.ESCROW_FUNDED},create:{bookingId:b.id,grossLamports:b.quotedLamports,status:PaymentStatus.ESCROW_FUNDED}})]); return {ok:true,status:'FUNDED',signature,escrowAddress:escrow.toBase58()};});

app.get('/bookings/:id/settlement-preview',async(req,reply)=>{const s=await requireSession(req,reply,redis);if(!s)return;const {id}=z.object({id:z.string().cuid()}).parse(req.params);const b=await db.booking.findFirst({where:{id,OR:[{buyerId:s.userId},{listing:{ownerId:s.userId}}]},include:{payment:true}});if(!b||!b.payment)return reply.code(404).send({error:'not_found'});const x=calculateSettlement(b.payment.grossLamports,b.validSeconds,b.expectedSeconds,config.COMMISSION_BPS);return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,typeof v==='bigint'?v.toString():v]))});
app.post('/internal/sweep-offline',async(req,reply)=>{if(!constantTimeToken(req.headers.authorization?.replace(/^Bearer\s+/i,''),config.INTERNAL_SERVICE_TOKEN))return reply.code(401).send({error:'unauthorized'});const cutoff=new Date(Date.now()-config.HEARTBEAT_OFFLINE_SECONDS*1000);const rows=await db.machine.findMany({where:{lastHeartbeatAt:{lt:cutoff},connectivity:MachineConnectivity.ONLINE},select:{id:true}});const ids=rows.map(x=>x.id);if(ids.length)await db.$transaction([db.machine.updateMany({where:{id:{in:ids}},data:{connectivity:MachineConnectivity.OFFLINE,operational:MachineOperational.UNAVAILABLE}}),db.gpuListing.updateMany({where:{machineId:{in:ids},status:ListingStatus.ACTIVE},data:{status:ListingStatus.HIDDEN_OFFLINE}})]);return {hidden:ids.length}});
await app.register(fastifyStatic,{root:path.resolve(process.cwd(),'../web'),prefix:'/'});
app.setNotFoundHandler((req,reply)=>{if(req.method==='GET'&&!req.url.startsWith('/api/')&&!req.url.startsWith('/internal/'))return reply.sendFile('index.html');return reply.code(404).send({error:'not_found'})});
const shutdown=async(signal:string)=>{app.log.info({signal},'shutdown');await app.close();await db.$disconnect();redis.disconnect();process.exit(0)};
process.once('SIGTERM',()=>void shutdown('SIGTERM'));process.once('SIGINT',()=>void shutdown('SIGINT'));
await app.listen({host:'0.0.0.0',port:config.PORT});
